//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaWeb.SoapPessoa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaPerfil3", Namespace="nsProxyRFBCNJ")]
    [System.SerializableAttribute()]
    public partial class PessoaPerfil3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoCadastralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenteExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePaisExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMaeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaturezaOcupacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcupacaoPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExercicioOcupacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoLogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroLogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeAdministrativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoObitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstrangeiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAtualizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SituacaoCadastral {
            get {
                return this.SituacaoCadastralField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoCadastralField, value) != true)) {
                    this.SituacaoCadastralField = value;
                    this.RaisePropertyChanged("SituacaoCadastral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResidenteExterior {
            get {
                return this.ResidenteExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenteExteriorField, value) != true)) {
                    this.ResidenteExteriorField = value;
                    this.RaisePropertyChanged("ResidenteExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigoPaisExterior {
            get {
                return this.CodigoPaisExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisExteriorField, value) != true)) {
                    this.CodigoPaisExteriorField = value;
                    this.RaisePropertyChanged("CodigoPaisExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NomePaisExterior {
            get {
                return this.NomePaisExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePaisExteriorField, value) != true)) {
                    this.NomePaisExteriorField = value;
                    this.RaisePropertyChanged("NomePaisExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NomeMae {
            get {
                return this.NomeMaeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMaeField, value) != true)) {
                    this.NomeMaeField = value;
                    this.RaisePropertyChanged("NomeMae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataNascimentoField, value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NaturezaOcupacao {
            get {
                return this.NaturezaOcupacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NaturezaOcupacaoField, value) != true)) {
                    this.NaturezaOcupacaoField = value;
                    this.RaisePropertyChanged("NaturezaOcupacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string OcupacaoPrincipal {
            get {
                return this.OcupacaoPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.OcupacaoPrincipalField, value) != true)) {
                    this.OcupacaoPrincipalField = value;
                    this.RaisePropertyChanged("OcupacaoPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ExercicioOcupacao {
            get {
                return this.ExercicioOcupacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExercicioOcupacaoField, value) != true)) {
                    this.ExercicioOcupacaoField = value;
                    this.RaisePropertyChanged("ExercicioOcupacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TipoLogradouro {
            get {
                return this.TipoLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoLogradouroField, value) != true)) {
                    this.TipoLogradouroField = value;
                    this.RaisePropertyChanged("TipoLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string NumeroLogradouro {
            get {
                return this.NumeroLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroLogradouroField, value) != true)) {
                    this.NumeroLogradouroField = value;
                    this.RaisePropertyChanged("NumeroLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CodigoMunicipio {
            get {
                return this.CodigoMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMunicipioField, value) != true)) {
                    this.CodigoMunicipioField = value;
                    this.RaisePropertyChanged("CodigoMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string DDD {
            get {
                return this.DDDField;
            }
            set {
                if ((object.ReferenceEquals(this.DDDField, value) != true)) {
                    this.DDDField = value;
                    this.RaisePropertyChanged("DDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string UnidadeAdministrativa {
            get {
                return this.UnidadeAdministrativaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeAdministrativaField, value) != true)) {
                    this.UnidadeAdministrativaField = value;
                    this.RaisePropertyChanged("UnidadeAdministrativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string AnoObito {
            get {
                return this.AnoObitoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoObitoField, value) != true)) {
                    this.AnoObitoField = value;
                    this.RaisePropertyChanged("AnoObito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Estrangeiro {
            get {
                return this.EstrangeiroField;
            }
            set {
                if ((object.ReferenceEquals(this.EstrangeiroField, value) != true)) {
                    this.EstrangeiroField = value;
                    this.RaisePropertyChanged("Estrangeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string DataAtualizacao {
            get {
                return this.DataAtualizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAtualizacaoField, value) != true)) {
                    this.DataAtualizacaoField = value;
                    this.RaisePropertyChanged("DataAtualizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string TituloEleitor {
            get {
                return this.TituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloEleitorField, value) != true)) {
                    this.TituloEleitorField = value;
                    this.RaisePropertyChanged("TituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroField, value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CNPJPerfil3", Namespace="nsProxyRFBCNJ")]
    [System.SerializableAttribute()]
    public partial class CNPJPerfil3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstabelecimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeEmpresarialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoCadastralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSituacaoCadastralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaturezaJuridicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNAEPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LojaWeb.SoapPessoa.ArrayOfString CNAESecundarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoLogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroLogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDD1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDD2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFResponsavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeResponsavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapitalSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LojaWeb.SoapPessoa.Socio[] SociedadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCRCContadorPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificacaoCRCContadorPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCRCContadorPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFCRCContadorPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJContadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCRCContadorPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificacaoCRCContadorPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCRCContadorPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFCRCContadorPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFContadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpcaoSimplesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataOpcaoSimplesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataExclusaoSimplesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJSucedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LojaWeb.SoapPessoa.ArrayOfString CNPJSucessoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estabelecimento {
            get {
                return this.EstabelecimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstabelecimentoField, value) != true)) {
                    this.EstabelecimentoField = value;
                    this.RaisePropertyChanged("Estabelecimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeEmpresarial {
            get {
                return this.NomeEmpresarialField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeEmpresarialField, value) != true)) {
                    this.NomeEmpresarialField = value;
                    this.RaisePropertyChanged("NomeEmpresarial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeFantasia {
            get {
                return this.NomeFantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeFantasiaField, value) != true)) {
                    this.NomeFantasiaField = value;
                    this.RaisePropertyChanged("NomeFantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SituacaoCadastral {
            get {
                return this.SituacaoCadastralField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoCadastralField, value) != true)) {
                    this.SituacaoCadastralField = value;
                    this.RaisePropertyChanged("SituacaoCadastral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DataSituacaoCadastral {
            get {
                return this.DataSituacaoCadastralField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSituacaoCadastralField, value) != true)) {
                    this.DataSituacaoCadastralField = value;
                    this.RaisePropertyChanged("DataSituacaoCadastral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CidadeExterior {
            get {
                return this.CidadeExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeExteriorField, value) != true)) {
                    this.CidadeExteriorField = value;
                    this.RaisePropertyChanged("CidadeExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisField, value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NomePais {
            get {
                return this.NomePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePaisField, value) != true)) {
                    this.NomePaisField = value;
                    this.RaisePropertyChanged("NomePais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NaturezaJuridica {
            get {
                return this.NaturezaJuridicaField;
            }
            set {
                if ((object.ReferenceEquals(this.NaturezaJuridicaField, value) != true)) {
                    this.NaturezaJuridicaField = value;
                    this.RaisePropertyChanged("NaturezaJuridica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DataAbertura {
            get {
                return this.DataAberturaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAberturaField, value) != true)) {
                    this.DataAberturaField = value;
                    this.RaisePropertyChanged("DataAbertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CNAEPrincipal {
            get {
                return this.CNAEPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.CNAEPrincipalField, value) != true)) {
                    this.CNAEPrincipalField = value;
                    this.RaisePropertyChanged("CNAEPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public LojaWeb.SoapPessoa.ArrayOfString CNAESecundario {
            get {
                return this.CNAESecundarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CNAESecundarioField, value) != true)) {
                    this.CNAESecundarioField = value;
                    this.RaisePropertyChanged("CNAESecundario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TipoLogradouro {
            get {
                return this.TipoLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoLogradouroField, value) != true)) {
                    this.TipoLogradouroField = value;
                    this.RaisePropertyChanged("TipoLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string NumeroLogradouro {
            get {
                return this.NumeroLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroLogradouroField, value) != true)) {
                    this.NumeroLogradouroField = value;
                    this.RaisePropertyChanged("NumeroLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string CodigoMunicipio {
            get {
                return this.CodigoMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMunicipioField, value) != true)) {
                    this.CodigoMunicipioField = value;
                    this.RaisePropertyChanged("CodigoMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string NomeMunicipio {
            get {
                return this.NomeMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMunicipioField, value) != true)) {
                    this.NomeMunicipioField = value;
                    this.RaisePropertyChanged("NomeMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string DDD1 {
            get {
                return this.DDD1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DDD1Field, value) != true)) {
                    this.DDD1Field = value;
                    this.RaisePropertyChanged("DDD1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Telefone1 {
            get {
                return this.Telefone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefone1Field, value) != true)) {
                    this.Telefone1Field = value;
                    this.RaisePropertyChanged("Telefone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string DDD2 {
            get {
                return this.DDD2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DDD2Field, value) != true)) {
                    this.DDD2Field = value;
                    this.RaisePropertyChanged("DDD2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Telefone2 {
            get {
                return this.Telefone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefone2Field, value) != true)) {
                    this.Telefone2Field = value;
                    this.RaisePropertyChanged("Telefone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string CPFResponsavel {
            get {
                return this.CPFResponsavelField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFResponsavelField, value) != true)) {
                    this.CPFResponsavelField = value;
                    this.RaisePropertyChanged("CPFResponsavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string NomeResponsavel {
            get {
                return this.NomeResponsavelField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeResponsavelField, value) != true)) {
                    this.NomeResponsavelField = value;
                    this.RaisePropertyChanged("NomeResponsavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string CapitalSocial {
            get {
                return this.CapitalSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.CapitalSocialField, value) != true)) {
                    this.CapitalSocialField = value;
                    this.RaisePropertyChanged("CapitalSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public LojaWeb.SoapPessoa.Socio[] Sociedade {
            get {
                return this.SociedadeField;
            }
            set {
                if ((object.ReferenceEquals(this.SociedadeField, value) != true)) {
                    this.SociedadeField = value;
                    this.RaisePropertyChanged("Sociedade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string TipoCRCContadorPJ {
            get {
                return this.TipoCRCContadorPJField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCRCContadorPJField, value) != true)) {
                    this.TipoCRCContadorPJField = value;
                    this.RaisePropertyChanged("TipoCRCContadorPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string ClassificacaoCRCContadorPJ {
            get {
                return this.ClassificacaoCRCContadorPJField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificacaoCRCContadorPJField, value) != true)) {
                    this.ClassificacaoCRCContadorPJField = value;
                    this.RaisePropertyChanged("ClassificacaoCRCContadorPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string NumeroCRCContadorPJ {
            get {
                return this.NumeroCRCContadorPJField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCRCContadorPJField, value) != true)) {
                    this.NumeroCRCContadorPJField = value;
                    this.RaisePropertyChanged("NumeroCRCContadorPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string UFCRCContadorPJ {
            get {
                return this.UFCRCContadorPJField;
            }
            set {
                if ((object.ReferenceEquals(this.UFCRCContadorPJField, value) != true)) {
                    this.UFCRCContadorPJField = value;
                    this.RaisePropertyChanged("UFCRCContadorPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string CNPJContador {
            get {
                return this.CNPJContadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJContadorField, value) != true)) {
                    this.CNPJContadorField = value;
                    this.RaisePropertyChanged("CNPJContador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string TipoCRCContadorPF {
            get {
                return this.TipoCRCContadorPFField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCRCContadorPFField, value) != true)) {
                    this.TipoCRCContadorPFField = value;
                    this.RaisePropertyChanged("TipoCRCContadorPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string ClassificacaoCRCContadorPF {
            get {
                return this.ClassificacaoCRCContadorPFField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificacaoCRCContadorPFField, value) != true)) {
                    this.ClassificacaoCRCContadorPFField = value;
                    this.RaisePropertyChanged("ClassificacaoCRCContadorPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string NumeroCRCContadorPF {
            get {
                return this.NumeroCRCContadorPFField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCRCContadorPFField, value) != true)) {
                    this.NumeroCRCContadorPFField = value;
                    this.RaisePropertyChanged("NumeroCRCContadorPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string UFCRCContadorPF {
            get {
                return this.UFCRCContadorPFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFCRCContadorPFField, value) != true)) {
                    this.UFCRCContadorPFField = value;
                    this.RaisePropertyChanged("UFCRCContadorPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string CPFContador {
            get {
                return this.CPFContadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFContadorField, value) != true)) {
                    this.CPFContadorField = value;
                    this.RaisePropertyChanged("CPFContador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string Porte {
            get {
                return this.PorteField;
            }
            set {
                if ((object.ReferenceEquals(this.PorteField, value) != true)) {
                    this.PorteField = value;
                    this.RaisePropertyChanged("Porte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string OpcaoSimples {
            get {
                return this.OpcaoSimplesField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcaoSimplesField, value) != true)) {
                    this.OpcaoSimplesField = value;
                    this.RaisePropertyChanged("OpcaoSimples");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string DataOpcaoSimples {
            get {
                return this.DataOpcaoSimplesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataOpcaoSimplesField, value) != true)) {
                    this.DataOpcaoSimplesField = value;
                    this.RaisePropertyChanged("DataOpcaoSimples");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string DataExclusaoSimples {
            get {
                return this.DataExclusaoSimplesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataExclusaoSimplesField, value) != true)) {
                    this.DataExclusaoSimplesField = value;
                    this.RaisePropertyChanged("DataExclusaoSimples");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string CNPJSucedida {
            get {
                return this.CNPJSucedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJSucedidaField, value) != true)) {
                    this.CNPJSucedidaField = value;
                    this.RaisePropertyChanged("CNPJSucedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public LojaWeb.SoapPessoa.ArrayOfString CNPJSucessora {
            get {
                return this.CNPJSucessoraField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJSucessoraField, value) != true)) {
                    this.CNPJSucessoraField = value;
                    this.RaisePropertyChanged("CNPJSucessora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroField, value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="nsProxyRFBCNJ", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Socio", Namespace="nsProxyRFBCNJ")]
    [System.SerializableAttribute()]
    public partial class Socio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PercentualParticipacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePaisOrigemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PercentualParticipacao {
            get {
                return this.PercentualParticipacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PercentualParticipacaoField, value) != true)) {
                    this.PercentualParticipacaoField = value;
                    this.RaisePropertyChanged("PercentualParticipacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigoPaisOrigem {
            get {
                return this.CodigoPaisOrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisOrigemField, value) != true)) {
                    this.CodigoPaisOrigemField = value;
                    this.RaisePropertyChanged("CodigoPaisOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NomePaisOrigem {
            get {
                return this.NomePaisOrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePaisOrigemField, value) != true)) {
                    this.NomePaisOrigemField = value;
                    this.RaisePropertyChanged("NomePaisOrigem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="nsProxyRFBCNJ", ConfigurationName="SoapPessoa.ISOAPService")]
    public interface ISOAPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="nsProxyRFBCNJ#ConsultarCPFP3", ReplyAction="nsProxyRFBCNJ/ISOAPService/ConsultarCPFP3Response")]
        LojaWeb.SoapPessoa.PessoaPerfil3[] ConsultarCPFP3(string ListaDeCPF, string CPFUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="nsProxyRFBCNJ#ConsultarCPFP3", ReplyAction="nsProxyRFBCNJ/ISOAPService/ConsultarCPFP3Response")]
        System.Threading.Tasks.Task<LojaWeb.SoapPessoa.PessoaPerfil3[]> ConsultarCPFP3Async(string ListaDeCPF, string CPFUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="nsProxyRFBCNJ#ConsultarCNPJP3", ReplyAction="nsProxyRFBCNJ/ISOAPService/ConsultarCNPJP3Response")]
        LojaWeb.SoapPessoa.CNPJPerfil3[] ConsultarCNPJP3(string CNPJ, string CPFUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="nsProxyRFBCNJ#ConsultarCNPJP3", ReplyAction="nsProxyRFBCNJ/ISOAPService/ConsultarCNPJP3Response")]
        System.Threading.Tasks.Task<LojaWeb.SoapPessoa.CNPJPerfil3[]> ConsultarCNPJP3Async(string CNPJ, string CPFUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPServiceChannel : LojaWeb.SoapPessoa.ISOAPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPServiceClient : System.ServiceModel.ClientBase<LojaWeb.SoapPessoa.ISOAPService>, LojaWeb.SoapPessoa.ISOAPService {
        
        public SOAPServiceClient() {
        }
        
        public SOAPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LojaWeb.SoapPessoa.PessoaPerfil3[] ConsultarCPFP3(string ListaDeCPF, string CPFUsuario) {
            return base.Channel.ConsultarCPFP3(ListaDeCPF, CPFUsuario);
        }
        
        public System.Threading.Tasks.Task<LojaWeb.SoapPessoa.PessoaPerfil3[]> ConsultarCPFP3Async(string ListaDeCPF, string CPFUsuario) {
            return base.Channel.ConsultarCPFP3Async(ListaDeCPF, CPFUsuario);
        }
        
        public LojaWeb.SoapPessoa.CNPJPerfil3[] ConsultarCNPJP3(string CNPJ, string CPFUsuario) {
            return base.Channel.ConsultarCNPJP3(CNPJ, CPFUsuario);
        }
        
        public System.Threading.Tasks.Task<LojaWeb.SoapPessoa.CNPJPerfil3[]> ConsultarCNPJP3Async(string CNPJ, string CPFUsuario) {
            return base.Channel.ConsultarCNPJP3Async(CNPJ, CPFUsuario);
        }
    }
}
